### ISSUE TITLE
Issues with poetry 1.6 / 1.6.1 pulling in own python version

### ISSUE THREAD

**Issue by timkpaine** [conda-forge/poetry-feedstock#93] opened 2023-10-05 20:18 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Seeing this across a few conda-forge packages:

https://github.com/conda-forge/gotrue-feedstock/runs/17443079855

```
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/conda/feedstock_root/build_artifacts/gotrue_1696535357058/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/poetry/core/masonry/__init__.py", line 10, in <module>
    from .builder import Builder
  File "/home/conda/feedstock_root/build_artifacts/gotrue_1696535357058/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/poetry/core/masonry/builder.py", line 5, in <module>
    from poetry.core.utils._compat import Path
  File "/home/conda/feedstock_root/build_artifacts/gotrue_1696535357058/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/poetry/core/utils/_compat.py", line 8, in <module>
    import six.moves.urllib.parse as urllib_parse
ModuleNotFoundError: No module named 'six.moves'

```

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by timkpaine** [comment] 2023-10-05 20:19
`/lib/python3.12/importlib/__init__.py", line 90, in import_module`

maybe related to https://github.com/python-poetry/poetry/issues/8507

**Comment by xylar** [comment] 2023-10-05 22:08
@timkpaine, I can't quite understand it but if you actually look at the CI you linked to above, it's pulling in:
```
    poetry:             1.1.15-pyhd8ed1ab_1       conda-forge
    poetry-core:        1.0.7-pyhd8ed1ab_1        conda-forge
```
These are some very old versions, not 1.6 or 1.6.1.  My guess is that they're the cause of the problem.  I think the issue is that we haven't build `poetry` for python 3.12 yet and you're getting a very old version of poetry that must have an incorrect constraint on python, whereas you should be getting an error that poetry isn't available for python 3.12 yet.

**Comment by xylar** [comment] 2023-10-05 22:13
Hmm, sorry, that's not right.  Poetry is `noarch: python` so it shouldn't require python 3.12 migration and the python constraint includes python 3.12. So I'm still baffled.

**Comment by xylar** [comment] 2023-10-05 22:24
I can reproduce the problem locally with:
```
mamba create -y -n test python=3.12 poetry pip
```
I also get:
```
poetry                    1.1.15             pyhd8ed1ab_1    conda-forge
poetry-core               1.0.7              pyhd8ed1ab_1    conda-forge
```

When I try:
```
mamba create -y -n test pip "poetry>=1.6" python=3.12
```
I get a solver failure that I don't yet understand.

**Comment by xylar** [comment] 2023-10-05 22:28
@timkpaine, I think the real effect of adding `poetry <1.6` to your recipes was to downgrade the version of python used in the host environment to 3.11 at which point things worked out.

**Comment by xylar** [comment] 2023-10-05 22:52
I believe this problem is caused, at least in part, by a CI failure after this PR was merged:
https://github.com/conda-forge/dulwich-feedstock/pull/83

**Comment by xylar** [comment] 2023-10-06 17:55
Next problem is with rapidfuzz < 3.0.0.  I will try to fix this, starting with adding myself as a maintainer:
https://github.com/conda-forge/rapidfuzz-feedstock/pull/153

**Comment by xylar** [comment] 2023-10-07 12:25
Fixing the issue in:
https://github.com/conda-forge/rapidfuzz-feedstock/pull/155

**Comment by xylar** [comment] 2023-10-07 15:30
The following is now working:
```
mamba create -y -n test python=3.12 "poetry>=1.2" pip
```
and creates an environment with `poetry 1.6.1` and `poetry-core 1.7.0`, so I think this can be closed.

**Closed as completed by xylar** 2023-10-07 15:30 UTC
Labels: bug
